# Run docker-compose up
# Live long and prosper
version: '3'
services:
  rabbitmq:
    container_name: skf-rabbitmq_container
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin-skf-secret
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    container_name: skf-mysql_container
    image: mariadb:${MARIADB_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: "skf"
      MYSQL_ROOT_PASSWORD: "admin-skf-secret"
      MYSQL_DEFAULT_PASS: "admin-skf-secret"
      MYSQL_DEFAULT_USER: "root"
    volumes:
      - /var/lib/docker/volumes/bf1ddb79db29f4aa5afbacd89c1b0d6e9e817da280acf446a4de342771fe994f/_data:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    container_name: skf-nginx_container
    restart: always
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./Docker/compose/site.conf:/etc/nginx/nginx.conf
      - ./Docker/compose/proxy_config.pac:/usr/share/nginx/html/proxy_config.pac
    ports:
      - "80:80"
  skf-angular:
    container_name: skf-angular_container
    build:
      context: ./
      dockerfile: ./Docker/alpine-cloud/angular/Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    image: "pei/skf-angular:${SKF_VERSION}"
    environment:
      - FRONTEND_URI=http://localhost
      - AUTH_METHOD=skiploginprovider
  skf-api:
    container_name: skf-api_container
    build:
      context: ./
      dockerfile: ./Docker/alpine-cloud/api/Dockerfile
      args:
        - VERSION=${SKF_VERSION}
        - SKF_API_PYTHON_VERSION=${SKF_API_PYTHON_VERSION}
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    volumes:
      - ~/.kube/config:/home/user_api/.kube/config
    image: "pei/skf-api:${SKF_VERSION}"
    env_file: Docker/alpine-cloud/api/api.env

  zap:
    build:
      context: ./Docker/zap/
      dockerfile: Dockerfile
      args:
        - VERSION=${ZAP_VERSION}
    container_name: skf-zap
    depends_on:
      - skf-api
      - skf-angular
    restart: always
    image: "pei/skf-zap2docker-stable:${ZAP_VERSION}"
    volumes:
      - zapwork:/zap/wrk:rw
    ports:
      - '7070:8080'
      - '7090:7090'
    environment:
      - ZAP_WEBSWING_OPTS=-host 0.0.0.0 -port 7090 -certpubdump /zap/wrk/owasp_zap_root_ca.cer -certfulldump  /zap/wrk/owasp_zap_root_ca.key
    user: zap
    command: 'zap-webswing.sh'

  firefox:
    build:
      context: ./Docker/firefox/
      dockerfile: Dockerfile
      args:
        - VERSION=${FIREFOX_VERSION}
    container_name: skf-firefox
    depends_on:
      - zap
    restart: on-failure:3
    image: "pei/skf-firefox:${FIREFOX_VERSION}"
    shm_size: '2gb'
    tmpfs:
      - /config
    volumes:
      - zapwork:/config/zap:rw
    ports:
      - '5800:5800'
    env_file: Docker/firefox/firefox.env

  cyberchef:
    build:
      context: ./Docker/docker-cyberchef/
      dockerfile: Dockerfile
      args:
        - VERSION=${CYBERCHEF_VERSION}
    container_name: skf-cyberchef
    restart: on-failure:3
    image: "pei/skf-cyberchef:${CYBERCHEF_VERSION}"
    ports:
      - '8000:8000'

volumes:
  zapwork:
    driver_opts:
      type: tmpfs
      device: tmpfs
