version: 2.1
date: 25/02/2022
profiles:
  - id: '1'
    name: Secure Development
    text: >-
      This profile is dedicated for developers (Blue security Champions) who want to learn secure
      development.
    iconClass: bx-shield
    courses:
      - id: '1.0'
        name: Easy - Secure Development crash course
        text: Easy - Secure Development crash course
        iconClass: bx-shield
        courseFile: training/courses/1.0-quickstart--easy.yaml
      - id: '1.1'
        name: Easy - Secure Development course
        text: Easy - Secure Development course
        iconClass: bx-shield
        courseFile: training/courses/1.1-secdev--easy--.yml
      - id: '1.2'
        name: Competent - Secure Development course
        text: Competent - Secure Development course
        iconClass: bx-shield
        courseFile: training/courses/1.2-secdev--competent--.yml
      - id: '1.3'
        name: Advanced - Secure Development course
        text: Advanced - Secure Development course
        iconClass: bx-shield
        courseFile: training/courses/1.3-secdev--advanced--.yml
  - id: '2'
    name: Hacking web & API
    text: >-
      This profile is dedicated for security pentesters or developers (Red security Champions) 
      who want to learn the basics and advanced techniques of penetration testing for Web & API
      applications. This course is based on the OWASP WSTG and teach you how to
      perform a good quality penetrationt test.
    iconClass: bx-code-block
    courses:
      - id: '2.1'
        name: Easy - Hacking web & API
        text: Easy - Hacking web & API
        iconClass: bx-code-block
        courseFile: training/courses/2.1-hacking--easy--.yml
      - id: '2.2'
        name: Competent - Hacking web & API
        text: Competent - Hacking web & API
        iconClass: bx-code-block
        courseFile: training/courses/2.2-hacking--competent--.yml
      - id: '2.3'
        name: Advanced - Hacking web & API
        text: Advanced - Hacking web & API
        iconClass: bx-code-block
        courseFile: training/courses/2.3-hacking--advanced--.yml
  - id: '3'
    name: Infra & Ops
    text: >-
      This profile is dedicated for Ops and Infra people who want to learn about
      the server hardening and security best practices. This course is inspired on
      the VulnHub materials and lessons to teach the best practices for server
      configurations and hardening.
    iconClass: bx-server
    courses: 
      - id: '3.1'
        name: Easy - The Infra & Ops Security 
        text: Let's see how an attacker approaches your network, 
          are you ready to learn the Infra vulnerabilities?
        iconClass: bx-code-block
        courseFile: training/courses/3.1-infra--easy--.yml    
  - id: '4'
    name: OWASP
    text: >-
      This profile is dedicated for security pentesters or developers to get familiar 
      with all the OWASP projects and tools. Here you will have the
      possibility to play and learn from the best OWASP projects in an easy way.
    iconClass: bx-fingerprint
    courses:
      - id: '4.1'
        name: The OWASP Top 10 2021 
        text: This is the OWASP top 10 2021 release, 
          are you ready to learn the top 10 vulnerabilities?
        iconClass: bx-code-block
        courseFile: training/courses/4.1-owasp--top10--.yml
      - id: '4.2'
        name: The OWASP Cheatsheets 
        text: This is the OWASP cheatsheets, 
          practical guidance of most important ASVS topics.
        iconClass: bx-code-block
        courseFile: training/courses/4.2-owasp--cheatsheets--.yml
      - id: '4.3'
        name: The OWASP Pro Active controls 
        text: This is the OWASP Pro Active controls, 
          practical guidance secure coding implementation and design patterns.
        iconClass: bx-code-block
        courseFile: training/courses/4.3-owasp--proactive--.yml