apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-back
data:
  SKF_JWT_SECRET: Super_secret_change_me_13123
  SKF_API_URL: "https://secureby.design/api"
  SKF_FLASK_DEBUG: "False"
  #SKF_DB_URL: sqlite:///db/db.sqlite
  SKF_DB_URL: mysql+pymysql://root:admin-skf-secret@mysql/skf?charset=utf8mb4
  SKF_DOJO_API_KEY: optional
  SKF_TESTING: "False"
  SKF_LABS_DOMAIN: "https://skf-labs.training"
  SKF_LABS_DEPLOY_MODE: "subdomain"
  # or use the below to use subdomains to deploy the Labs by creating a subdomain Wildcard that points to the Labs IP cluster
  #SKF_LABS_DEPLOY_MODE: "subdomain"
  RABBIT_MQ_CONN_STRING: rabbitmq
  ORIGIN: skf-flask-back
  #GOOGLE_CREDENTIALS: base64_string_here_of_the_content_of_the gsa-key.json file_for_example: cat gsa-key.json | base64
  LABS_KUBE_CONF:   LABS_KUBE_CONF: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljY_update_me...
  #LABS_KUBE_CONF: base64_string_here_of_the_content_of_the .kube/config file_for_example: cat ~/.kube/config | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skf-flask-front
data:
  FRONTEND_URI: https://secureby.design
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin-skf-secret
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_ROOT_PASSWORD: admin-skf-secret
  MYSQL_DEFAULT_USER: root
  MYSQL_DEFAULT_PASS: admin-skf-secret
  MYSQL_DATABASE: skf
---  
